### ISSUE TITLE
Markdown links causing error

### ISSUE THREAD

**Issue by tobyhage** [tyrion/gridsome-plugin-netlify-cms-paths#5]
Hello,

Thank you for this plugin :-)

When i use a markdown link for example:

`[mailto](mailto:example@gmail.com)`

There is an error during the build.

Error: /static/uploads/mailto:example@gmail.com was not found

at throwError (/node_modules/gridsome/lib/app/build/executeQueries.js:21:13)
    at pMap (/node_modules/gridsome/lib/app/build/executeQueries.js:50:9)

**Comment by tyrion** [comment]
This should be fixed in master. It would be great if you could confirm.
Thanks for reporting the issue.

**Comment by tobyhage** [comment]
Yes now it is working. Thank you very much!
Can you also update the npm package :-)

**Comment by tyrion** [comment]
Done
